version: '3'
services: 

  nginx:
    image: nginx:1
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "flask"

  flask:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env_prod
  